import { QueryProvider } from "@/providers/query-provider"
import { ThemeProvider } from "@/providers/theme-provider"
import { AuthSessionProvider } from "@b4se/auth/react"
import { DM_Sans } from "next/font/google"
import { Toaster } from "sileo"
import "./global.css"

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
  display: "swap"
})

export const metadata = {
  title: "Welcome to sub",
  description: "Generated by create-nx-workspace"
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es" className={`dark ${dmSans.variable}`}>
      <body className="font-sans antialiased">
        <AuthSessionProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <QueryProvider>{children}</QueryProvider>
          </ThemeProvider>
          <Toaster position="top-right" theme="system" />
        </AuthSessionProvider>
      </body>
    </html>
  )
}
